### ISSUE TITLE
[问题] Exception : Service Intent must be explicit

### ISSUE THREAD

**Issue by fxleyu** [fxleyu/nougat#45]
### 环境
> android 8.0

### 异常信息
```
Process: com.android.xxxxxx, PID: 10832
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.xxx.xxxx.action.xxx.input (has extras) }
	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1465)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1506)
	at android.app.ContextImpl.startService(ContextImpl.java:1478)
	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
```

**Comment by fxleyu** [comment]
# 解决方案
```java
Intent intent = new Intent(ACTION_OF_SERVICE);

List<ResolveInfo> resolveInfoList = context.getPackageManager()
        .queryIntentServices(intent, -1/*all*/);
if (resolveInfoList == null || resolveInfoList.size() != 1) {
    Log.d(TAG, "[WTF] Not Service to handle this action : " + ACTION_OF_SERVICE);
    return;
}

ServiceInfo serviceInfo = resolveInfoList.get(0).serviceInfo;
intent.setClassName(emodeServiceInfo.packageName, emodeServiceInfo.name);
context.startService(intent);
```

### 引用
- http://blog.android-develop.com/2014/10/android-l-api-21-javalangillegalargumen.html

**Comment by fxleyu** [comment]
# 遗留任务
#46 学习`PackageManager`相关的内容，这是一种最佳实践形式。

**Comment by fxleyu** [comment]
#46
